centrifugo:
  extends:
    file: common-services.yml
    service: centrifugo

media:
  extends:
    file: common-services.yml
    service: media
  volumes:
    - /static

app:
  extends:
    file: common-services.yml
    service: app
  command: uwsgi --ini uwsgi.ini #python manage.py runserver 0.0.0.0:8000
  links:
    - centrifugo
  volumes_from:
    - media
  environment:
    - DJANGO_SETTINGS_MODULE=natr.settings.dev
    - SERVE_STATIC=false

nginx:
  extends:
    file: common-services.yml
    service: nginx
  volumes_from:
    - media
  volumes:
    - ./static:/static
  links:
    - app
